virttool/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
import os 

BASEDIR = os.path.abspath(os.path.dirname(__file__))

urlpatterns = patterns('',

    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'virt.views.home.logout_view', name='sys_logout'),


    # admin
    (r'^admin/', include(admin.site.urls)),
    
    ('^$', 'django.views.generic.simple.redirect_to', {'url': '/virt/'}),
    
    
    
    
    # virttool interface 
    (r'^virt/', include('virt.urls')),
    
    # static files 
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': BASEDIR + '/media/'}),
    
    
)

virttool/virt/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('',
    url(r'^$', 'virt.views.home.index', name="home"),
    
    # Node 
    url(r'^node/$', 'virt.views.node.index', name="node_get"),
    url(r'^node/add/$', 'virt.views.node.add', name="node_add"),    
    url(r'^node/(\d+)/$', 'virt.views.node.edit', name="node_edit"),  
    url(r'^node/(\d+)/updatedomains/$', 'virt.views.node.updatedomains', name="node_updatedomains"),  
    url(r'^node/(\d+)/updatecapabilities/$', 'virt.views.node.updatecapabilities', name="node_updatecapabilities"),
    
    url(r'^node/(\d+)/delete/$', 'virt.views.node.delete', name="node_delete"),       
    url(r'^node/save/$', 'virt.views.node.save', name="node_save"),    
    
    # Domain
    url(r'^domain/$', 'virt.views.domain.index', name="domain_get"),
    url(r'^domain/add/$', 'virt.views.domain.add', name="domain_add"),    
    url(r'^domain/(\d+)/$', 'virt.views.domain.edit', name="domain_edit"),  
    url(r'^domain/(\d+)/delete/$', 'virt.views.domain.delete', name="domain_delete"),
    url(r'^domain/save/$', 'virt.views.domain.save', name="domain_save"),
    
    # Device
    url(r'^domain/(\d+)/device/(\w+)/add/$', 'virt.views.device.add', name="device_add"),
    url(r'^device/(\d+)/$', 'virt.views.device.edit', name="device_edit"),
    url(r'^device/(\d+)/attach/$', 'virt.views.device.attachdevice', name="device_attach"),
    url(r'^device/(\d+)/detach/$', 'virt.views.device.detachdevice', name="device_detach"),
    
    url(r'^device/(\d+)/delete/$', 'virt.views.device.delete', name="device_delete"),
    url(r'^device/save/$', 'virt.views.device.save', name="device_save"),
    
    
    
    
    # libvirt domain actions 
    url(r'^domain/(\d+)/migrate/(\d+)/$', 'virt.views.domain.migrate', name="domain_migrate"),
    url(r'^domain/(\d+)/create/$', 'virt.views.domain.create', name="domain_create"),
    url(r'^domain/(\d+)/resume/$', 'virt.views.domain.resume', name="domain_resume"),
    url(r'^domain/(\d+)/suspend/$', 'virt.views.domain.suspend', name="domain_suspend"),
    url(r'^domain/(\d+)/reboot/$', 'virt.views.domain.reboot', name="domain_reboot"),
    url(r'^domain/(\d+)/shutdown/$', 'virt.views.domain.shutdown', name="domain_shutdown"),
    url(r'^domain/(\d+)/destroy/$', 'virt.views.domain.destroy', name="domain_destroy"),
      
    
    

)

virttool/virt/models.py
from django.db import models
from django.db.models import F,Q
import libvirt
from lib.app import snmp, xmltool
from django.utils.translation import ugettext as _
from constants import * 
import fields
from virt import helpforms
import settings

class Node(models.Model):    
    
    name = models.CharField(_('Name'), max_length=100, unique=True)
    
    def __unicode__(self):
        return self.name
        
    hostname = models.CharField(_('Hostname'), max_length=255, help_text=helpforms.NODE_HOSTNAME)
    uri = models.CharField(_('URI'), max_length=255, null=True, blank=True, default=None)
    description = models.CharField(_('Description'), blank=False, max_length=255)
    type = models.IntegerField(_('Node Type'), default=0, choices=VIRT_INTERFACE_NAME, \
                                                          help_text=helpforms.NODE_TYPE)
    state = models.IntegerField(default=0, choices=NODE_STATE)
    capabilities = models.TextField(null=True,blank=True)
    defaultbridge = models.CharField(_('Bridge Default'), max_length=50, null=True, blank=True, \
                                            default=None, help_text=helpforms.NODE_DEFAULTBRIDGE)
    active = models.BooleanField(_('Active'), default=True,null=False)
    datecreated = models.DateTimeField(auto_now_add=True, null=False)
    datemodified = models.DateTimeField(auto_now=True, null=False)
    
    
    def getlibvirt(self):
        """
          Return instance libvirt.virConnect and 
          dict(libvirt.libvirtError[code,message])
        """

        VIRT_INTERFACE_ = VIRT_INTERFACE_URI[self.type] %self.hostname
        URI = self.uri or VIRT_INTERFACE_
        try:
            return libvirt.open(URI), None                       
        except libvirt.libvirtError, le:
            return None, dict(code=le.get_error_code(), msg=le.get_error_message())
    
    
    def update_capabilities(self,autosave=True,libvirtnode=None):
        """
          Update name, capabilities, state from libvirt 
        """
        if libvirtnode:
            libvirtnode_, error_ = libvirtnode,None
        else:
            libvirtnode_, error_ = self.getlibvirt()
        if libvirtnode_:
            self.capabilities = libvirtnode_.getCapabilities()
            self.state = 1
        else:
            self.state = 2            
        if autosave == True:
            self.save()

            
    def getnetdev(self,version=1,community="public"):
        """
          Get network interfaces via SNMP 
        """
        snmp_ = snmp.Snmp()
        devlist = []
        NOTLISTED=['vif','lo']
        
        for dev in snmp_.snmpwalk(self.hostname,"1.3.6.1.2.1.2.2.1.2",version,community):
            invalidfound = False
            for nl in NOTLISTED:
                if dev.split('STRING:')[1].strip().startswith(nl):
                    invalidfound=True
            if invalidfound == False:
                devlist.append(dev.split('STRING:')[1].strip())
        return devlist
                    

    def import_domains(self,libvirtnode=None):
        """
          Import all domains from Node 
        """        
        if libvirtnode:
            libvirtnode_, erro_ = libvirtnode, None
        else:
            libvirtnode_, error_ = self.getlibvirt()
            
        if libvirtnode_:
            libvirtdomains = [ libvirtnode_.lookupByID(ID) for ID in libvirtnode_.listDomainsID()[1:] ]
            for libvirtdomain in libvirtdomains:
                
                # import domains
                if Domain.objects.filter(name=libvirtdomain.name()).count() == 0:
                    new_domain = Domain()
                    new_domain.name=libvirtdomain.name()
                    new_domain.description='Virtual Machine %s' %libvirtdomain.name()
                    new_domain.node=self
                    new_domain.state=libvirtdomain.info()[0]
                    
                    if self.defaultbridge:
                        options = dict(defaultbridge=self.defaultbridge)
                    else:
                        options = None
                        
                    xmlf = xmltool.getxml(libvirtdomain.XMLDesc(0), options)
                    new_domain.type = xmlf.get('type')
                    new_domain.xml= xmlf.get('domain')
                    new_domain.save()
                    
                    # import devices
                    for d in xmlf.get('devices'):
                        new_device = Device()
                        new_device.domain = new_domain
                        new_device.type = d.get('type')
                        new_device.xml = d.get('xml')
                        new_device.save()

                #else:
                #    existing_domain = Domain.objects.get(name=libvirtdomain.name())
                #    existing_domain.state = libvirtdomain.info()[0]
                #    existing_domain.xml= xmltool.formatxml(libvirtdomain.XMLDesc(0))
                #    existing_domain.save()
                        
    

    def getdict(self):
        """
           Return Capabilities dictionary python 
        """
        return xmltool.get_capabilities_dict(self.capabilities)
        
                        
    class Meta:
        ordering = 'name',
        verbose_name = _('Node')
        verbose_name_plural = (_('Nodes'))
        


class Domain(models.Model):

    node = models.ForeignKey(Node, verbose_name=_('Node'))
    name = models.CharField(_('Name'), max_length=100)
    uuid = models.CharField(_('UUID'), max_length=36,blank=True)
    hostname = models.CharField(_('Host'), max_length=200, blank=True, null=True, default=None)
    description = models.CharField(_('Description'), blank=False, max_length=200)
    type = models.CharField(_('Type'), max_length=20, choices=DOM_TYPES)
    xml = models.TextField(_('XML'))
    autostart = models.BooleanField(_('Auto start'), default=True)
    priority = models.IntegerField(_('Priority'), default=10)    
    state = models.IntegerField(default=0, choices=DOMAIN_STATE)
    datecreated = models.DateTimeField(auto_now_add=True, null=False)
    datemodified = models.DateTimeField(auto_now=True, null=False)
    
    
    def getlibvirt(self,libvirtnode=None):
        """
          Return Domain libvirt
        """     
          
        if libvirtnode:
            libvirtnode_, error_ = libvirtnode, None
        else:
            libvirtnode_, error_ = self.node.getlibvirt()
        try:    
            return libvirtnode_.lookupByName(self.name), error_
        except:
            return None, error_
            
    
    def update_state(self,libvirtnode=None):
        """
           Update state Domain 
        """
        
        # 96 = Powered Off by user, 97 = Wait Migrate, 99 = Disabled
        if self.state not in [96,97,99]:   
            change=False         
            state = self.state
            libvirtdomain, error_ = self.getlibvirt(libvirtnode)
            if libvirtdomain:
                state_ = libvirtdomain.info()[0]
                if state_ != state:
                    change=True
                    self.state = state_
            else:
                self.state = 98
                change=True
                
            if change == True:
                self.save()
    
    
    #
    #  GETs Devices 
    #
    
    def getemulator(self):
        return self.device_set.filter(type='emulator')
    def getdisk(self):
        return self.device_set.filter(type='disk')                            
    def getinterface(self):
        return self.device_set.filter(type='interface')        
    def getgraphics(self):
        return self.device_set.filter(type='graphics')
    def getinput(self):
        return self.device_set.filter(type='input')
    def getconsole(self):
        return self.device_set.filter(type='console')
    def getserial(self):
        return self.device_set.filter(type='serial')
    def getparallel(self):
        return self.device_set.filter(type='parallel')
    def getchannel(self):
        return self.device_set.filter(type='channel')    
    def getsound(self):
        return self.device_set.filter(type='sound')
    def getvideo(self):
        return self.device_set.filter(type='video')
    def gethostdev(self):
        return self.device_set.filter(type='hostdev')
    def getcontroller(self):
        return self.device_set.filter(type='controller')
            
    
    
    def getdict(self):
        """
           Return Domain dictionary python 
        """
        return xmltool.get_domain_dict(self.xml)
                    
    
    def getxml(self):
        """
           Return Domain XML Format 
        """
        
        xmldomain = str()
        xmldomain = self.xml

        xmldomain = xmldomain.replace('</domain>','')
        xmldomain+="<devices>\n"
        for devicetype in ['emulator',
                           'disk',
                           'controller',
                           'interface',
                           'graphics',
                           'input',
                           'parallel',
                           'serial',
                           'console',
                           'channel',
                           'sound',
                           'video',
                           'hostdev']:
            for dxml in self.device_set.filter(type=devicetype):
                xmldomain+="%s\n" %dxml.xml
        xmldomain+="</devices>\n</domain>"

        return xmldomain
            
    
    def __unicode__(self):
        return self.name 
        
        
    class Meta:
        ordering = 'name',
        verbose_name = _('Domain')
        verbose_name_plural = (_('Domains'))

        
#
#  Transport Domain
#
class Transport(models.Model):
    node = models.ForeignKey(Node, verbose_name=_('Node'))
    domain = models.ForeignKey(Domain, verbose_name=_('Domain'))

    def __unicode__(self):

virttool/virt/views/base.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse

virttool/virt/views/home.py
from base import * 
from django.utils.translation import ugettext as _
from django.contrib.auth import logout

def index(request):      
    return render_to_response('virt/index.html',{}, context_instance=RequestContext(request))
    
def logout_view(request):
    logout(request)    
    return HttpResponseRedirect(reverse('home'))

virttool/templates/virt/domainadd.html
{% extends "virt/base.html" %}



{% block content %}

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#domainop').addClass("current_page_item");
    
    
    $('#id_on_poweroff').attr('value', 'destroy');
    $('#id_on_reboot').attr('value', 'restart');
    $('#id_on_crash').attr('value', 'restart');
    
    
  });
</script>

<style type="text/css" media="screen">
        #id_name, #id_uuid, #id_description {  width: 300px; }
        #id_memory, #id_currentMemory, #id_vcpus { width: 90px; }
        #id_os_kernel, #id_os_initrd, #id_os_cmdline { width: 300px;}
        #id_os_type, #id_os_loader { width: 300px; }
</style>
{% load extras %}

<div class="post">


	<div class="post_title"><h2><a href="#">Create Domain</a></h2></div>
	<div class="post_date"> <a href="#"></a></div>
	<div class="post_body">

        <form class="formx" action="{% url domain_add %}" method="post">

            {% for field in form %}
            <p> 
                {{ field.label_tag }} {{ field }} 
                {% if field.errors %}
                <span class="fielderror"> {% for error in field.errors %} {{ error }} &nbsp; {% endfor %} </span>
                {% endif %}
                {% if field.help_text %}
                    <br/><span class="help"> {{ field.help_text }} </span>
                {% endif %}
                
            </p>    
            {% endfor %}
        
             <p>
                  <input class="form_bt_adicionar" type="submit" value="Create" />
               </p>
          
        </form>
        	<div class="clearer">&nbsp;</div>
	</div>
	


</div>



{% endblock %}

virttool/templates/virt/domainedit.html
{% extends "virt/base.html" %}
{% load i18n extras %}
{% block menu2 %}
		<ul>
			<li class="current_page_item"><a href="{% url domain_edit domain.id %}"> {% trans "Domain Info" %}</a></li>
			<li class="current_page_item"><a href=""> &nbsp; {% trans "Transport" %}</a></li>
			<li class="current_page_item"><a href=""> &nbsp; {% trans "Graphics" %}</a></li>
		</ul>

{% endblock %}

{% block content %}

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#domainop').addClass("current_page_item");
    
  });
</script>


<style type="text/css" media="screen">
    #id_name, #id_uuid, #id_description {  width: 300px; }
    #id_memory, #id_currentMemory, #id_vcpus { width: 90px; }
    #id_os_kernel, #id_os_initrd, #id_os_cmdline { width: 300px;}
    #id_os_type, #id_os_loader { width: 300px; }
</style>


<div class="post">

	<div class="post_title"><h2><a href="#">Domain {{ domain.name }}</a></h2></div>
	<div class="post_date"> <a href="#"></a></div>
	<div class="post_body">
	  	
        <div class="post_meta" style="font-size: 12px;">
            <h3> Domain Info </h3>
             Node: <a href="{% url node_edit domain.node.id %}"> {{ domain.node.name }} </a> <br/>
    	     Last State {{ domain.get_state_display }} <br/>
    	     <br/>
    	     

    	</div>
    	
	  	 
            <input class="form_bt_cancelar" style="float: right;" type="submit" value="{% trans "Destroy" %}" onclick="if (confirm('Confirm Destroy ?')) { 
            window.location='{% url domain_destroy domain.id %}'}"/>
            
            <input class="form_bt_reboot" style="float: right;" type="submit" value="{% trans "Reboot" %}" onclick="if (confirm('Confirm Reboot ?')) { 
             window.location='{% url domain_reboot domain.id %}'}"/>            
        
            <input class="form_bt_alterar" style="float: right;" type="submit" value="{% trans "Shutdown" %}" onclick="if (confirm('Confirm Shutdown ?')) { 
            window.location='{% url domain_shutdown domain.id %}'}"/>
                        
            <input class="form_bt_salvar" style="float: right;" type="submit" value="{% trans "Suspend" %}" onclick="if (confirm('Confirm Suspend ?')) { 
            window.location='{% url domain_suspend domain.id %}'}"/>
            <input class="form_bt_ativar" style="float: right;" type="submit" value="{% trans "Resume" %}" onclick="if (confirm('Confirm Resume ?')) { 
            window.location='{% url domain_resume domain.id %}'}"/>            
            <input class="form_bt_adicionar" style="float: right;" type="submit" value="{% trans "Create" %}" onclick="if (confirm('Confirm Create ?')) { 
            window.location='{% url domain_create domain.id %}'}"/>
            
            
        <div class="clear"> &nbsp; </div>    	  	  	  	  
	  	      
	    <form class="formx" action="{% url domain_save %}" method="post">

            <input type="hidden" name="id" value="{{ domain.id }}" id="id"/>    
            {% for field in form %}
            <p>    
                {{ field.label_tag }} {{ field }} 
                 {% if field.errors %}
                    <span class="fielderror"> {% for error in field.errors %} {{ error }} &nbsp; {% endfor %} </span>
                    {% endif %}
                    {% if field.help_text %}
                        <br/><span class="help"> {{ field.help_text }} </span>
                    {% endif %}
            </p>    
            {% endfor %}
            
              <p>
                  <input class="form_bt_alterar" type="submit" value="Save" />
               </p>
        </form>
    <br/>
    <br/>

    
    <h3 class="diskicon"> Disks </h3>
    <a style="float: right;" href="{% url device_add domain.id 'disk' %}"> {% trans "Add" %} </a>
    <table class="tablex" border="0" cellpadding="0" cellspacing="0">
     <tr>
         <th> Device </th>
         <th> Type </th>        
         <th> Driver </th>
         <th> Target </th>
         <th> Source </th>   
         <th> Options </th>
         <th> &nbsp; </th>
      </tr>
      {% for disk in domain.getdisk %}
        <tr>
              <td> {{ disk.getdict.device }} </td> 
              <td> {{ disk.getdict.disk_type }} </td>
              <td> {{ disk.getdict.driver_name }}</td>
              <td> {% if disk.getdict.target_bus %} {{ disk.getdict.target_bus }} &nbsp; - {% endif %}
                   {{ disk.getdict.target }}
              </td>
              <td> {{ disk.getdict.source }} </td>
              <td> 
                    {% if disk.getdict.readonly %} Read Only <br/>{% endif %}
                    {% if disk.getdict.args %} {{ disk.getdict.args }} {% endif %} 
              </td>
              <td> <a class="edit" href="{% url device_edit disk.id %}">&nbsp;</a> 
                   <a class="remove" href="{% url device_delete disk.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
              </td>
        </tr>
      {% endfor %}
    
    </table>
    
    <br/> 

    <br/>
      
    
    

    <br/>
    <h3 class="interfaceicon"> Network Interfaces </h3>
    <a style="float: right;" href="{% url device_add domain.id 'interface' %}"> {% trans "Add" %} </a>
    <table class="tablex" border="0" cellpadding="0" cellspacing="0">
     <tr>
         <th> Type </th>
         <th> Source </th>
         <th> Target </th>
         <th> Mac Address </th>
         <th> Options </th>
         <th>  &nbsp;  </th>
    </tr>
    
    {% for interface in domain.getinterface %}
    <tr>
        <td> {{ interface.getdict.interface_type }} </td>
        <td> {{ interface.getdict.source }} </td>
        <td> {{ interface.getdict.target }} </td>
        <td> {{ interface.getdict.mac|upper }} </td>
        <td>
             {% if interface.getdict.other_args %} {{ interface.getdict.other_args }} {% endif %}
        </td>
        <td> <a class="edit" href="{% url device_edit interface.id %}">&nbsp;</a> 
             <a class="remove" href="{% url device_delete interface.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
        </td>
        
    </tr>

    {% endfor %}
    
    </table>
    
    <br/>
    
    <br/>
    <h3 class="graphicsicon"> Graphics </h3>
    <a style="float: right;" href="{% url device_add domain.id 'graphics' %}"> {% trans "Add" %} </a>
    <table class="tablex" border="0" cellpadding="0" cellspacing="0">
     <tr>
         <th> Type </th>
         <th> Options </th>
         <th>  &nbsp;  </th>
    </tr>
    
    {% for graphics in domain.getgraphics %}
    <tr>
        <td> {{ graphics.getdict.graphics_type }} </td>
        <td> </td>
         <td> <a class="edit" href="{% url device_edit graphics.id %}">&nbsp;</a> 
                 <a class="remove" href="{% url device_delete graphics.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
            </td>
    </tr>

    {% endfor %}
    
    </table>
    <br/>
    
    <h3 class="inputicon"> Inputs </h3>
    <a style="float: right;" href="{% url device_add domain.id 'input' %}"> {% trans "Add" %} </a>
    <table class="tablex" border="0" cellpadding="0" cellspacing="0">
     <tr>
         <th> Type </th>
         <th> Bus </th>
         <th>  &nbsp;  </th>
    </tr>
    
    {% for input in domain.getinput %}
    <tr>
        <td> {{ input.getdict.input_type }} </td>
        <td> {{ input.getdict.bus }}</td>
        <td> <a class="edit" href="{% url device_edit input.id %}">&nbsp;</a> 
                 <a class="remove" href="{% url device_delete input.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
            </td>
    </tr>

    {% endfor %}
    
    </table>
    
    <br/>
    <h3 class="consoleicon"> Console </h3>
    <a style="float: right;" href="{% url device_add domain.id 'console' %}"> {% trans "Add" %} </a>
    <table class="tablex" border="0" cellpadding="0" cellspacing="0">
     <tr>
         <th> Source </th>
         <th> Target </th>
         <th>  &nbsp;  </th>
    </tr>
    
    {% for console in domain.getconsole %}
    <tr>
        <td> {{ console.getdict.source }} </td>
        <td> {{ console.getdict.target }}</td>
        <td> 
            <a class="edit" href="{% url device_edit console.id %}">&nbsp;</a> 
            <a class="remove" href="{% url device_delete console.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
        </td>
    </tr>

    {% endfor %}
    
    </table>
    
    
     <br/>
    <h3 class="serialicon"> Serial </h3>
    <a style="float: right;" href="{% url device_add domain.id 'serial' %}"> {% trans "Add" %} </a>
    <table class="tablex" border="0" cellpadding="0" cellspacing="0">
     <tr>
         <th> Source </th>
         <th> Target </th>
         <th>  &nbsp;  </th>
    </tr>
    
    {% for serial in domain.getserial %}
    <tr>
        <td> {{ serial.getdict.source }} </td>
        <td> {{ serial.getdict.target }}</td>
        <td> 
            <a class="edit" href="{% url device_edit serial.id %}">&nbsp;</a> 
            <a class="remove" href="{% url device_delete serial.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
        </td>
    </tr>

    {% endfor %}
    
    </table>
    <br/>
     
     <h3 class="emulatoricon"> Emulator </h3>
     <a style="float: right;" href="{% url device_add domain.id 'emulator' %}"> {% trans "Add" %} </a>
     <table class="tablex" border="0" cellpadding="0" cellspacing="0">
      <tr>
          <th> Path</th>
          <th>  &nbsp;  </th>
     </tr>

     {% for emulator in domain.getemulator %}
     <tr>
         <td> {{ emulator.getdict.emulator }} </td>
         <td> 
             <a class="edit" href="{% url device_edit emulator.id %}">&nbsp;</a> 
             <a class="remove" href="{% url device_delete emulator.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 
         </td>
     </tr>

     {% endfor %}

     </table>
     <br/>
     <br/>
     
     
     
    
  <br/><br/>

   
    </div>
	 <h3 class="xmlicon"> XML </h3>
	<div class="post_meta" style="font-size: 12px;">
	   
	      <pre>{{ domain.getxml }} </pre>
	</div>

</div>

<br/>
<br/>
<a class="remove" href="{% url domain_delete domain.id %}" onclick="return confirm('Confirm Delete ?');">&nbsp;</a> 

{% endblock %}

virttool/templates/virt/index.html
{% extends "virt/base.html" %}
{% load i18n %}

{% block menu2 %}
		<ul>
			<li><a href="{% url domain_add %}">{% trans "Create Domain" %} </a></li>
			<li><a href="{% url node_add %}"> {% trans "Create Node" %} </a></li>
			<li><a href="#">{% trans "Status" %} </a></li>
		</ul>

{% endblock %}
  
{% block content %}

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#homeop').addClass("current_page_item");
  });
</script>

<style type="text/css" media="screen">
    #content { height: 200px;}
</style>

<br/>
{% endblock %}

virttool/templates/virt/nodeadd.html
{% extends "virt/base.html" %}
{% load i18n %}

<script src="/static/js/jquery-validate/jquery.validate.js" type="text/javascript"></script>
<link rel="stylesheet" href="/static/css/box.css" type="text/css" media="screen" charset="utf-8">



{% block content %}

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#nodeop').addClass("current_page_item");
    
    $('#showhelp').click(function() {       
       $('#driverhelp').slideDown('normal');        
    });
    
    $('#closehelp').click(function() {       
       $('#driverhelp').hide();
    });
    
    
  });
</script>

<style type="text/css" media="screen">
    #id_description { width: 300px; }
    #id_hostname { width: 200px; }
    #id_uri { width: 400px; }
     #id_type { width: 200px;}
</style>

{% load extras %}

<div class="post">

	<div class="post_title"><h2><a href="#">Create Node</a></h2></div>
	<div class="post_date"> <a href="#"></a></div>
	<div class="post_body">
	

<form class="formx" action="{% url node_add %}" method="post">
    
    {% for field in form %}
    <p>    
        {{ field.label_tag }} {{ field }} 
        {% if field.name == 'uri' %} <a href="#" id="showhelp"> {% trans "Help" %} </a>
          <div class="post_meta" style="font-size: 12px; display:none;" id="driverhelp">
              <a href="#" id="closehelp" style="float:right;"> {% trans "Close" %} </a>
              <h3> URI Help </h3>
      	    <pre>{{ URIHELP }}</pre>
      	</div>
        {% endif %}
        
         {% if field.errors %}
            <span class="fielderror"> {% for error in field.errors %} {{ error }} &nbsp; {% endfor %} </span>
            {% endif %}
            {% if field.help_text %}
                <br/><span class="help"> {{ field.help_text }} </span>
            {% endif %}
            
    </p>    
    {% endfor %}
    
           
    <p>
        <label for="importdomains"> Import Domains </label>
        <input type="checkbox" name="importdomains" id="importdomains"/>
          <br/><span class="help"> {% trans "If checked, the system will list all domain of the node and import them" %}</span>
    </p>
        <p>
          <input class="form_bt_adicionar" type="submit" value="Create" />
       </p>
       
</form>
 <br/>
	</div>
	


</div>



{% endblock %}